In [2]:
import pandas as pd
import numpy as np
from scipy.stats import ttest_ind
from scipy.stats import stats
import re

In [3]:
#open the file
fhandle = 'university_towns.txt'
univ = open(fhandle)
data = []

#parse each row and append state and RegioName to the list data
for row in univ:
     if '[edit]' in row:
        state = row[:re.search('\[', row).start()]
     else:
        if ' (' in row:
            RegionName = row[:re.search(' \(',row).start()] 
            data.append([state, RegionName])
        elif ' (' not in row:
            RegionName = row.rstrip()
            data.append([state, RegionName])


def get_list_of_university_towns():
     univ = pd.DataFrame(data, columns = ["State", "RegionName"])
     #st = pd.Series(states)
     #st = st.to_frame(name=None)
     #st.columns = (['State'])  
     #univ_new = pd.merge(univ, st, how = 'left', left_index = True, right_on = 'State')
     return univ

get_list_of_university_towns()

             State                    RegionName
0          Alabama                        Auburn
1          Alabama                      Florence
2          Alabama                  Jacksonville
3          Alabama                    Livingston
4          Alabama                    Montevallo
5          Alabama                          Troy
6          Alabama                    Tuscaloosa
7          Alabama                      Tuskegee
8           Alaska                     Fairbanks
9          Arizona                     Flagstaff
10         Arizona                         Tempe
11         Arizona                        Tucson
12        Arkansas                   Arkadelphia
13        Arkansas                        Conway
14        Arkansas                  Fayetteville
15        Arkansas                     Jonesboro
16        Arkansas                      Magnolia
17        Arkansas                    Monticello
18        Arkansas                  Russellville
19        Arkansas                        Searcy
20      California                        Angwin
21      California                        Arcata
22      California                      Berkeley
23      California                         Chico
24      California                     Claremont
25      California                        Cotati
26      California                         Davis
27      California                        Irvine
28      California                    Isla Vista
29      California  University Park, Los Angeles
..             ...                           ...
487       Virginia                          Wise
488       Virginia                    Chesapeake
489     Washington                    Bellingham
490     Washington                        Cheney
491     Washington                    Ellensburg
492     Washington                       Pullman
493     Washington  University District, Seattle
494  West Virginia                        Athens
495  West Virginia                    Buckhannon
496  West Virginia                      Fairmont
497  West Virginia                     Glenville
498  West Virginia                    Huntington
499  West Virginia                    Montgomery
500  West Virginia                    Morgantown
501  West Virginia                 Shepherdstown
502  West Virginia                  West Liberty
503      Wisconsin                      Appleton
504      Wisconsin                    Eau Claire
505      Wisconsin                     Green Bay
506      Wisconsin                     La Crosse
507      Wisconsin                       Madison
508      Wisconsin                     Menomonie
509      Wisconsin                     Milwaukee
510      Wisconsin                       Oshkosh
511      Wisconsin                   Platteville
512      Wisconsin                   River Falls
513      Wisconsin                 Stevens Point
514      Wisconsin                      Waukesha
515      Wisconsin                    Whitewater
516        Wyoming                       Laramie

[517 rows x 2 columns]